version: '3'
services:
    
    nuget.server:
        image: "loicsharma/baget:0b46f0ec87216e1dc6839277712ee07c1c2b611a"
        container_name: nuget.server
        ports:
            - 8080:80
        environment:
            - NUGET_API_KEY

    storage.emulator:
        image: "mcr.microsoft.com/azure-storage/azurite:3.11.0"
        container_name: storage.emulator
        ports:
            - 10000:10000
            - 10001:10001
        depends_on:
            - nuget.server
        command: azurite --loose --blobHost 0.0.0.0 --queueHost 0.0.0.0 --skipApiVersionCheck

    leasecalc.spinup:
        container_name: leasecalc.spinup
        build:
            context: .
            dockerfile: spinup.Dockerfile
        environment:
            - AzureStorageConnection
        depends_on:
            - storage.emulator

    leasecalc.insurance.api:
        container_name: leasecalc.insurance.api
        build:
            context: .
            dockerfile: insurance.api.Dockerfile
        ports:
            - 5000:5000

    leasecalc.functions:
        container_name: leasecalc.functions
        build:
            context: .
            dockerfile: functions.Dockerfile
        ports:
            - 80:80
        environment:
            - AzureStorageConnection
            - InsuranceApi
            - NuGetEndpoint
            - LeaseCalcMailerEmailAddress
            - MailJetPublicKey
            - MailJetPrivateKey
            - AZURE=true
        depends_on:
            - storage.emulator
            - nuget.server
            - leasecalc.insurance.api
        links:
            - leasecalc.insurance.api
            - storage.emulator
            - nuget.server