version: '3'
services:
    nuget.server:
        #x64
        #image: "loicsharma/baget:0b46f0ec87216e1dc6839277712ee07c1c2b611a"
        #ARM64
        image: "hub4rpi64/baget"
        container_name: nuget.server
        ports:
            - 8080:80
        environment:
            - NUGET_API_KEY

    azurite:
        image: "mcr.microsoft.com/azure-storage/azurite:3.11.0"
        container_name: azurite
        build:
            context: .
            dockerfile: spinup.Dockerfile
        ports:
            - 10000:10000
            - 10001:10001
        depends_on:
            - nuget.server

    leasecalc.spinup:
        container_name: leasecalc.spinup
        build:
            context: .
            dockerfile: spinup.Dockerfile
        environment:
            - AzureStorageConnection
        depends_on:
            - azurite

    leasecalc.insurance.api:
        container_name: leasecalc.insurance.api
        build:
            context: .
            dockerfile: insurance.api.Dockerfile
        ports:
            - 5000:5000

    leasecalc.functions:
        container_name: leasecalc.functions
        build:
            context: .
            dockerfile: functions.Dockerfile
        ports:
            - 80:80
        environment:
            - AzureStorageConnection
            - InsuranceApi
            - NuGetEndpoint
            - LeaseCalcMailerEmailAddress
            - MailJetPublicKey
            - MailJetPrivateKey
            - AZURE=true
        depends_on:
            - azurite
            - nuget.server
            - leasecalc.insurance.api
        links:
            - leasecalc.insurance.api
            - azurite
            - nuget.server